15below.Deployment.Database/Database.cs, 15below.Deployment.ReportingServices/MsReportingServices.cs
Fixes to correctly handle when the reporting user does not have a domain.
Pass "DisableOutput=true" to roundhouse to prevent flattening the scripts run
=> Report User & Roundhouse Fixes

deployHelp.ps1
Take into account the octopus variable name change from "Step" to "Action"
Also adding "Octopus.Only" which means you can call a variable "Octopus.Only.MyReallyLongContent" and this will not be added to an environment variable
=> Update logic for pulling octopus variables into environment variables

dnsHelper.ps1
These are optional functions and can be used in conjunction with the checking if a record exists and creating new records.
It enables a deployment script to alert on deployment if the record in place is incorrect.
=> Add functions to DNS helper to check if CNAME and A records point to the correct place

src/15below.Deployment.Update.Tests/TagDictionaryTestFiles/webservice-structure.xml, src/15below.Deployment.Update.Tests/TagDictionaryTests.cs, src/15below.Deployment.Update/NDjangoExpansions/DefaultFilter.cs, src/15below.Deployment.Update/NDjangoExpansions/EmptyFilter.cs, src/15below.Deployment.Update/NDjangoExpansions/ExistsFilter.cs, src/15below.Deployment.Update/NDjangoWrapper.cs
When errors occur in rendering (in particular rules) throw exception stating rendering has failed.
This is the same as the behaviour when rendering tags.
However, when rendering tags we can state where the error occurred.
When the error is in the rules, this is not possible, so the template is output and not where the error occurred.
This at least gives a hint as to where you can look.
=> Improve Error Handling

src/15below.Deployment.ReportingServices/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/TagDictionaryTestFiles/webservice-structure.xml, src/15below.Deployment.Update.Tests/TagDictionaryTests.cs, src/15below.Deployment.Update/15below.Deployment.Update.csproj, src/15below.Deployment.Update/FixedStructure.xsd, src/15below.Deployment.Update/Properties/AssemblyInfo.cs, src/15below.Deployment.Update/TagDictionary.cs, src/15below.Deployment.Update/UpdateFile.cs, src/Deploy/ensconce.nuspec, src/Ensconce.Database.Tests/Properties/AssemblyInfo.cs, src/Ensconce/Properties/AssemblyInfo.cs
Features/Changes
- Add missing tests for groups with more than 1 label.
- Add ability to wrap multiple labels in a "Labels" nodes.
- Add ability to specify a single label as a "label" attribute (rather than as a single Label node).
- Allow "Property" nodes to be at the root of the property group as well as inside a "Properties" node as before.
- Add XSD for structure files and validate against it
=> Property Group Label Enhancements

paket.dependencies, paket.lock, src/15below.Deployment.ReportingServices/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/15below.Deployment.Update.Tests.csproj, src/15below.Deployment.Update.Tests/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/TagDictionaryTests.cs, src/15below.Deployment.Update.Tests/UpdateFileTests.cs, src/15below.Deployment.Update/Properties/AssemblyInfo.cs, src/Deploy/ensconce.nuspec, src/Ensconce.Database.Tests/Ensconce.Database.Tests.csproj, src/Ensconce.Database.Tests/Properties/AssemblyInfo.cs, src/Ensconce/Arguments.cs, src/Ensconce/DictionaryExport.cs, src/Ensconce/Ensconce.csproj, src/Ensconce/Program.cs, src/Ensconce/Properties/AssemblyInfo.cs, src/Ensconce/paket.references, src/Scripts/createWebSite.ps1, src/Scripts/createiis6app.ps1, src/Scripts/createiis7app.ps1, src/Scripts/deployHelp.ps1, src/Scripts/dnsHelper.ps1, src/Scripts/userManagement.ps1
Added a Loading/Loaded message to scripts to show what is loading and how long it took.
Added --dictionaryPostUrl argument and --dictionarySavePath which can be used to either save the entire tag dictionary locally, or post that dictionary to another location.
This means Ensconce could now generate config and post it to a configuration store the applications read from as well as updating configuration files.
=> PS1 Loading Messages & Tag Dictionary JSON Export

src/15below.Deployment.ReportingServices/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/TagDictionaryTests.cs, src/15below.Deployment.Update/15below.Deployment.Update.csproj, src/15below.Deployment.Update/NDjangoExpansions/ContainsFilter.cs, src/15below.Deployment.Update/NDjangoExpansions/DecryptFilter.cs, src/15below.Deployment.Update/NDjangoExpansions/EndsWithFilter.cs, src/15below.Deployment.Update/NDjangoExpansions/StartsWithFilter.cs, src/15below.Deployment.Update/NDjangoWrapper.cs, src/15below.Deployment.Update/Properties/AssemblyInfo.cs, src/Ensconce.Database.Tests/Properties/AssemblyInfo.cs, src/Ensconce/Properties/AssemblyInfo.cs, src/Scripts/userManagement.ps1
Functions to support string contains / startsWith / endsWith, and the ability to decrypt data using a certificate.
Examples:
{% if SomeValue|contains:'15below' %}true{% else %}false{% endif %}
{% if URL|startsWith:'https://' %}true{% else %}false{% endif %}
{% if HostName|endsWith:'.com' %}true{% else %}false{% endif %}
{{ EncryptedValue|decrypt:Certificate }} // decrypts the value using a certificate in the certificate store
Where Certificate would be a string of the CN of the certificate, i.e. "XX-NON-Certificate"
=> contains / startsWith / endsWith / decrypt support

src/15below.Deployment.ReportingServices/Properties/AssemblyInfo.cs, src/15below.Deployment.Update.Tests/Properties/AssemblyInfo.cs, src/15below.Deployment.Update/Properties/AssemblyInfo.cs, src/Deploy/ensconce.nuspec, src/Ensconce.Database.Tests/Properties/AssemblyInfo.cs, src/Ensconce.Logging/Properties/AssemblyInfo.cs, src/Ensconce/Properties/AssemblyInfo.cs, src/Scripts/createiis6app.ps1, src/Scripts/createiis7app.ps1
Useful for ASP.NET Core applications, where running an app pool with no managed runtime is optimal
=>  Add deploy script functions to set managed runtime versions

src/Ensconce.Database.Tests/TemporaryDatabaseTests.cs, src/Ensconce.Update.Tests/Ensconce.Update.Tests.csproj, src/Ensconce.Update.Tests/TestUpdateFiles/TestSubstitution30.xml, src/Ensconce.Update.Tests/UpdateFileTests.cs, src/Ensconce.Update/Substitutions.xsd, src/Ensconce.Update/UpdateFile.cs
This uses a "if" with any django if statement.
This if statement gets created into correct NDjango to validate
example:
```
<?xml version="1.0" encoding="utf-8" ?>
<Root xmlns="http://15below.com/Substitutions.xsd">
<Namespaces/>
<Files>
<File Filename="TestUpdateFiles\TestConfig3.xml">
<Changes>
<Change type="ChangeAttribute" XPath="/root/value" attributeName="myAttr" value="after" if="Environment == 'INT'" />
</Changes>
</File>
</Files>
</Root>
```
Dependent on https://github.com/15below/Ensconce/pull/86
_This PR contains everything which is also in that PR_
=> Add logic to turn a subsitution off and on

src/Ensconce.Console/TextRendering.cs, src/Ensconce.Update/TagDictionary.cs
This means if Ensconce is used to copy the fixed structure file you get a warning on that step, but it will still work.
But if a step fails because it cannot correctly parse tags, you will have a warning that there is no fixed structure file
=> Rather than hard failing when structure file cannot be found, just log warning

src/Ensconce.Console/Ensconce.Console.csproj, src/Ensconce.Console/ExceptionDetails.cs, src/Ensconce.Console/Program.cs, src/Ensconce.Console/Retry.cs, src/Ensconce.Console/TextRendering.cs, src/Ensconce.Update.Tests/TagDictionaryTests.cs, src/Ensconce.Update/NDjangoWrapper.cs, src/Ensconce.Update/TagDictionary.cs
Changes error output from:
Something went wrong. 
System.ArgumentException: Tag substitution errored on template string: 
{{ ClientCode }}-{{ Environment }}-Svc 
One or more errors occurred. 
at Ensconce.Update.NDjangoWrapper.Render(String template, Lazy`1 values, ITemplateManager templateManager) in E:\ba1\850655ce59456309\src\Ensconce.Update\NDjangoWrapper.cs:line 107 
at Ensconce.Console.Program.MainLogic(String[] args) in E:\ba1\850655ce59456309\src\Ensconce.Console\Program.cs:line 55 
at Ensconce.Console.Program.Main(String[] args) in E:\ba1\850655ce59456309\src\Ensconce.Console\Program.cs:line 14 
To:
Something went wrong.
>> InvalidDataException: PropertyGroup with identity 'AuntBetty' has no label attribute or nodes
at Ensconce.Update.TagDictionary.LabelPropertiesFromXml(XDocument …
=> Exception output to include inner exceptions, and ignoring certain exceptions from Retry

src/Ensconce.Console/ApplicationInteraction.cs
Prevents exceptions if the process is already terminating or terminated.
For testing:
```c#
var process = Process.Start("cmd");
process.Kill();
Thread.Sleep(1000); // Comment out delay to trigger terminating scenario, uncomment for terminated scenario.
const int Win32ErrorCodeAccessDenied = 5;
try
{
process.Kill();
}
catch (Win32Exception ex) when (ex.NativeErrorCode == Win32ErrorCodeAccessDenied)
{
// Process is already terminating.
Console.WriteLine("terminating");
}
catch (InvalidOperationException)
{
// Process has already terminated.
Console.WriteLine("terminated");
}
process.WaitForExit();
Console.WriteLine("exited");
```
=> Catch "already killed" exceptions when calling Process.Kill

docs/powershell/create-website/index.md, src/Scripts/createiis7app.ps1
Updates the the IIS7 website deployments to support the setting of an ip address when creating a new website or setting the SSL certificate and binding.
This is required if you wish to have multiple ssl certificates on windows server 2008 as it does not support multiple ssl certs on the same ip address.
Updates made to the following methods
CheckIfSslBindingExists - Adds checking of the ip address (default = "*")
CreateWebSite - adds optional ipAddress parameter (default = "*")
AddSslCertificate - adds optional ipAddress parameter (default = "*")
=> Add Support for setting an ip address when creating a new site or binding with IIS

build.cake, src/Ensconce.ReportingServices/SubscriptionInfoFileLoader.cs
This was not required in 1.6.x
=> Update emailBodyText in subinfo to not be required

build.cake, src/Scripts/dnsHelper.ps1
This change also has a more selective delete, as we can check the current type of the record.
We also ensure that we retain the TTL when we update records rather than reset to 3600
=> Update to DNS Helper to handle different TTL values

build.cake, src/Ensconce.Cake/EnsconceDeployDatabaseExtensions.cs, src/Ensconce.Cake/EnsconceDropDatabaseExtensions.cs, src/Ensconce.Cake/EnsconceFileUpdateExtensions.cs, src/Ensconce.Cli/DictionaryExport.cs, src/Ensconce.Cli/TagSubstitution.cs, src/Ensconce.Cli/TextRendering.cs, src/Ensconce.Update.Tests/TagDictionaryBuilderTests.cs, src/Ensconce.Update.Tests/TagDictionaryTestFiles/invalidStructure.xml, src/Ensconce.Update.Tests/TagDictionaryTests.cs, src/Ensconce.Update/TagDictionary.cs, src/Ensconce.Update/TagDictionaryBuilder.cs
If fixed structure file doesn't exist or the xml is invalid hard fail
This prevents invalid or missing files from causing strange hidden effects like a tag not existing.
=> Hard fail on missing or broken XML

build.cake, src/Ensconce.sln, src/Scripts/deployHelp.ps1, src/Scripts/powershell4Polyfill.ps1
Automatically load powershell 4 polyfill when when powershell major version is 4 or less
The powershell function `Clear-DnsClientCache` is added in powershell 5.
So this means that powershell 4 will be able to "support" it
=> Create polyfill for powershell 4

build.cake, src/Ensconce.Update.Tests/TagDictionaryTestFiles/webservice-structure.xml, src/Ensconce.Update.Tests/TagDictionaryTests.cs, src/Ensconce.Update/TagDictionary.cs
Flat groups do not have a nested "Properties" node so the logic was not picking up the "Property" nodes.
Also, found (when writing a test) that if you have 2 sets groups with the same idententity (e.g. numbers) it's impossible to do a identity filtered model for those.  So support the identifier parameter also having a "." (which cannot be in property names etc) so say you want label.identity.
=> Fix handingling Of Flat Groups

build.cake, src/Ensconce.Update.Tests/TestUpdateFiles/TestSubstitution38.xml, src/Ensconce.Update.Tests/UpdateFileTests.cs, src/Ensconce.Update/ProcessSubsitution.cs
If the xml file being updated has namespaces then the `ifNotExists` with a namespace doesn't work.
This fix means that the namespaces can also be used in the xPath for the `ifNotExists`
=> Fix usage of namespace in `ifNotExists`

build.cake, docs/powershell/kubernetes-helper/index.md, src/Deploy/deploy.ps1, src/Scripts/kubernetesHelper.ps1
Change assumes kubectl exists at `C:\KubeCtl\kubectl.exe` but can also already be provided in a variable `$KubeCtlExe` (or as an octopus variable)
=> Remove kubectl from being part of Ensconce

src/Scripts/azureHelper.ps1
Azure CLI can be very "chatty" on warnings
i.e. `WARNING: This can take a long time`
Which in an automated deployment envrionment isn't very useful
=> Add ` --only-show-errors` to azure cli commands

src/Ensconce.Cli/ApplicationInteraction.cs, src/Ensconce.Cli/Arguments.cs, src/Ensconce.Cli/FileInteraction.cs, src/Ensconce.Helpers/Retry.cs, src/Scripts/deployHelp.ps1
Situations where unknown processes (like an antivirus) has a handle locked on the file.
=> Introduce support for Handle.exe to remove handles in a directory after stopping services and processes

build.cake, docs/Gemfile.lock, src/Ensconce.NDjango.Core/Misc.fs, src/Ensconce.NDjango.Tests/MiscellaneousTags.cs, src/Scripts/kubernetesHelper.ps1
This splits list of groups on the index with the right value.
Then joins before the item, the items updated with new element in list, after the item.
=> Update regroup to handle if the input items being grouped on are not in order

src/Ensconce.Database.Tests/Ensconce.Database.Tests.csproj, src/Ensconce.NDjango.Core/Constants.fs, src/Ensconce.NDjango.Tests/BasicSyntax.cs, src/Ensconce.NDjango.Tests/Designer.cs, src/Ensconce.NDjango.Tests/Ensconce.NDjango.Tests.csproj, src/Ensconce.NDjango.Tests/Filters.cs, src/Ensconce.NDjango.Tests/IfTags.cs, src/Ensconce.NDjango.Tests/LoopTags.cs, src/Ensconce.NDjango.Tests/MiscellaneousTags.cs, src/Ensconce.NDjango.Tests/ReproducedIssues.cs, src/Ensconce.NDjango.Tests/TestDescriptor.cs, src/Ensconce.NDjango.Tests/TestsRunner.cs, src/Ensconce.ReportingServices.Tests/Ensconce.ReportingServices.Tests.csproj, src/Ensconce.Update.Tests/Ensconce.Update.Tests.csproj
Amended regex that parses filters to allow for whitespace before the argument
Added NUnit analyser into NDJango tests and applied recommendations
Also bumped up all the test projects to net 8.0, as 6.0 is EOL
=> BDB-1259: Default filter allows for whitespace before the filter argument

build.cake, src/Scripts/deployHelp.ps1
Ignore Octopus variables that are too large for environment variable. The deploy script fails if these variables are being added as an environment variable.
=> Ignore Octopus variables that are too large for environment variable
